export default {
  bio: [
    'I\'m a <span class="key-word">Full Stack Web Engineer</span> with over two years of experience building scalable, high-performing, and accessible web applications. I’ve delivered impactful solutions at <span class="key-word">Apple</span>, ranging from production-ready features in React and Next.js to leading UI projects with TypeScript and Vue. Check out my work in the Projects section and explore my professional background in the Work section!',

    'I believe learning is a lifelong process and enjoy sharing knowledge with peers. Whether collaborating with <span class="key-word">UX, accessibility, backend, or product teams</span>, I thrive in environments where problem solving, coding, and design intersect to create intuitive and reliable user experiences. My projects often combine technical rigor with a strong focus on usability and performance.',

    'I\'m always open to <span class="key-word">new opportunities</span> that challenge me to grow and contribute. Feel free to reach out for collaboration, business inquiries, or job opportunities. You can find my LinkedIn and GitHub on the homepage, and my email in the footer!',
  ],
  technicalSkills: [
    'React.js',
    'Next.js',
    'Vue.js',
    'TypeScript',
    'JavaScript',
    'Node.js',
    'Express.js',
    'Python',
    'Django',
    'HTML',
    'CSS',
    'SASS',
    'Vite',
    'Jest',
    'Vue Test Utils',
    'E2E Testing',
    'Git',
    'GitHub',
    'Agile',
    'Figma',
    'Sketch',
    'PhotoShop',
    'WordPress',
  ],
  softSkills: [
    'Collaboration',
    'Leadership',
    'Problem Solving',
    'Adaptability',
    'Communication',
    'Accountability',
    'Self-Learning',
    'Efficiency',
    'Personable',
    'Ambitious',
    'Passionate',
    'Customer Service',
  ],
};
